[features]
seeds = false
skip-lint = false
[programs.localnet]
fomo3dgame = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
fomo3dgame = "E4v2GucED4FRedDNY6rZGJmc9G5MjHXGkQtrpjwgkMUJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
